version: "3.7"
services:
  k8s-ansible:
    build:
      context: ./
      dockerfile: Dockerfile
    image: k8s-ansible
    container_name: k8s-ansible
    hostname: k8s-ansible
    volumes:
      - ./ansible:/ansible
    env_file: 
      - common.env