---
- name: Install docker
  command: "amazon-linux-extras install -y docker"
  become: yes

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes
    use: service
  become: yes

- name: Add work user into Docker group
  user:
    name: "{{ ec2_all.work_user }}"
    groups:
      - docker
  become: yes