---
- name: Setup k8s master
  hosts: k8s-master
  vars:
    ansible_user: "{{ ec2_all.work_user }}"
    ansible_ssh_private_key_file: "/root/.ssh/k8s-adm.pem"
  roles:
    - role: ./roles/os_init
    - role: ./roles/docker
    - role: ./roles/kubeadm

- name: Setup k8s node
  hosts: k8s-node
  vars:
    ansible_user: "{{ ec2_all.work_user }}"
    ansible_ssh_private_key_file: "/root/.ssh/k8s-adm.pem"
  roles:
    - role: ./roles/os_init
    - role: ./roles/docker
    - role: ./roles/kubeadm