---
- name: Setup k8s master
  hosts: k8s_master
  vars:
    ansible_user: "{{ ec2_all.work_user }}"
    ansible_ssh_private_key_file: "/root/.ssh/k8s-adm.pem"
    _work_dir: "/home/{{ ec2_all.work_user }}"
  roles:
    - role: ./roles/os_init
    - role: ./roles/docker
    - role: ./roles/kubeadm
  tasks:
    - name: Create config directory for save config
      file:
        path: "{{ _work_dir }}/.kube"
        state: directory

    - name: Copy config
      copy:
        src: "/etc/kubernetes/admin.conf"
        dest: "{{ _work_dir }}/.kube/config"
        owner: "{{ ec2_all.work_user }}"
        group: "{{ ec2_all.work_user }}"
        force: yes
        remote_src: yes
      become: yes

    - name: Add Flannel
      command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml"

    - name: Kubeadm init
      command: "kubeadm init --pod-network-cidr={{ k8s_all.network.cird }} --apiserver-advertise-address={{ ansible_eth0.ipv4.address }}"
      become: yes
      register: _kubeinit_result

    - debug: var=_kubeinit_result

- name: Setup k8s node
  hosts: k8s_node
  vars:
    ansible_user: "{{ ec2_all.work_user }}"
    ansible_ssh_private_key_file: "/root/.ssh/k8s-adm.pem"
  roles:
    - role: ./roles/os_init
    - role: ./roles/docker
    - role: ./roles/kubeadm