---
- name: Setup k8s master
  hosts: k8s_master
  vars:
    ansible_user: "{{ ec2_all.work_user }}"
    ansible_ssh_private_key_file: "/root/.ssh/k8s-adm.pem"
  roles:
    - role: ./roles/os_init
    - role: ./roles/docker
    - role: ./roles/kubeadm
  tasks:
    - name: Kubeadm init
      command: "kubeadm init --pod-network-cidr={{ k8s_all.network.cird }} --apiserver-advertise-address={{ ansible_eth0.ipv4.address }}"
      become: yes
      register: _kubeinit_result

    - debug: var=_kubeinit_result

- name: Setup k8s node
  hosts: k8s_node
  vars:
    ansible_user: "{{ ec2_all.work_user }}"
    ansible_ssh_private_key_file: "/root/.ssh/k8s-adm.pem"
  roles:
    - role: ./roles/os_init
    - role: ./roles/docker
    - role: ./roles/kubeadm